merge: (#4) exception handling
Pmanchu-Service/Pmanchu_BE_ver.POP pull request #5
Opened 2024-08-22 10:46 UTC by sunnyday0206

# 주요 변경사항
	- exception handling 추가
	
# 중점적으로 봐줬으면 하는 부분
	- 코드 한번 확인해주시면 감사하겠습니다.

2024-08-22 11:08 UTC, in-jun requested changes
GlobalExceptionFilter도 함께 포함해 주시기 바랍니다.

2024-08-22 13:43 UTC, ByunDohwi commented on src/main/java/org/example/pmanchu_be/global/error/exception/GlobalException.java
> +public class GlobalException extends RuntimeException {
LGTM
자비스 같은 경우에는 GlobalException대신 JobisEeception으로 하던데 저희도 PmanchuException 어떤가요?

2024-08-22 13:45 UTC, sunnyday0206 commented on src/main/java/org/example/pmanchu_be/global/error/exception/GlobalException.java
> +public class GlobalException extends RuntimeException {
반영해보겠습니다.

2024-08-22 23:39 UTC, sunnyday0206 commented on src/main/java/org/example/pmanchu_be/global/error/exception/GlobalException.java
> +public class GlobalException extends RuntimeException {
반영하였습니다.

2024-08-22 23:39 UTC, ByunDohwi commented
PmanchuException 아주 좋은 것 같습니다 굿굿

2024-08-23 01:44 UTC, in-jun commented on src/main/java/org/example/pmanchu_be/global/error/exception/GlobalException.java
> +public class GlobalException extends RuntimeException {
[1d3b9a2](https://github.com/Pmanchu-Service/Pmanchu_BE/pull/5/commits/1d3b9a2efaf84466013207f0761d10d1075e91d1)

2024-08-23 01:44 UTC, in-jun requested changes
LGTM

2024-08-23 01:45 UTC, in-jun approved these changes

2024-08-23 01:47 UTC, merged