merge: (#6) erd 작성
Pmanchu-Service/Pmanchu_BE_ver.POP pull request #7
Opened 2024-09-05 08:21 UTC by in-jun

# 주요 변경사항

erd 작성함

2024-09-05 09:12 UTC, 1408bg commented on README.md
> +    ProjectMember {
# 소유자 식별
Project의 소유자를 확인할 방법이 없다.
## 대처 방안
1. Project에 FK로 소유자 id 사용
2. ProjectMember에 역할 필드 추가

2024-09-10 12:52 UTC, ByunDohwi commented
보고서, 계획서 테이블 추가해주세요

2024-09-11 14:35 UTC, in-jun commented on README.md
> +    ProjectMember {
[8b25946](https://github.com/Pmanchu-Service/Pmanchu_BE/pull/7/commits/8b259467a78426f9610876916b1a5fd1ac3a611d)

2024-09-11 14:47 UTC, ByunDohwi reviewed
a

2024-09-11 14:47 UTC, ByunDohwi commented on README.md
> +    }
유저가 회원가입시, 자기소개, 전공, 링크, 연락처 등을 받는데 그러한 정보를 저장할 테이블이 없는 것 같습니다.

2024-09-11 14:47 UTC, ByunDohwi commented on README.md
> +    }
전공이나 링크는 여러개일 수도 있는 것을 고려해야합니다.

2024-09-11 14:49 UTC, ByunDohwi reviewed
abcd

2024-09-11 15:33 UTC, in-jun commented on README.md
> +    }
[48d14c6](https://github.com/Pmanchu-Service/Pmanchu_BE/pull/7/commits/48d14c67ded8b7a35353777234796687db70151c)

2024-09-11 16:13 UTC, sunnyday0206 commented on README.md
> +    UserSpecialization {
UserSpecialization이라는 DB명을 UserMajor로 바꾸는 것이 가독성에 더 좋을 것 같습니다.

2024-09-11 16:13 UTC, sunnyday0206 requested changes
테이블명 변경 요청합니다.

2024-09-11 16:19 UTC, in-jun commented on README.md
> +    UserSpecialization {
[8a1261a](https://github.com/Pmanchu-Service/Pmanchu_BE/pull/7/commits/8a1261a3b96b6920641561858848b3d8ac7f5020)

2024-09-11 23:25 UTC, sunnyday0206 approved these changes
변경 감사합니다. 👍

2024-09-12 13:47 UTC, 1408bg reviewed
## project 테이블 생성일
report랑 plan에는 create_at이 깨알같이 있는데, project에는 어째서 없는걸까요..?

2024-09-12 13:47 UTC, 1408bg commented on README.md
> +    Project {
~~새삼스럽긴 한데..~~
프로젝트 생성일은 없어도 되는건가요?

2024-09-14 10:34 UTC, ByunDohwi requested changes

2024-09-14 10:34 UTC, ByunDohwi commented on README.md
> +
![image](https://github.com/user-attachments/assets/59dd2ab2-1beb-4c12-b438-3287248fa016)
![image](https://github.com/user-attachments/assets/c5cdfa56-f58d-40ca-9346-cdcf6d0fe14c)
참고해서 plan, report 수정 부탁드립니다..
title이랑 content만 있는건 아쉬운것 같습니다

2025-03-12 08:28 UTC, merged