marge: (#8) 엔티티 세팅
Pmanchu-Service/Pmanchu_BE_ver.POP pull request #9
Opened 2024-09-11 10:21 UTC by ByunDohwi

ERD를 기반으로 엔티티와 패키지 파일을 설정합니다.

2024-09-22 23:22 UTC, in-jun requested changes
코드가 전반적으로 깔끔하네요. 감사합니다.

2024-09-22 23:22 UTC, in-jun commented on src/main/resources/application.yml
> +    url: jdbc:mysql://localhost:3306/${DB_URL}
localhost도 환경변수로 수정해주세요. ex) `${DB_HOST}`

2024-09-22 23:22 UTC, in-jun commented on src/main/resources/application.yml
> +    url: jdbc:mysql://localhost:3306/${DB_URL}
`${DB_URL}` 보다는 `${DB_NAME}` 이 적당한 것 같습니다.

2024-09-23 00:17 UTC, ByunDohwi commented on src/main/resources/application.yml
> +    url: jdbc:mysql://localhost:3306/${DB_URL}
b301d2f68573f019003d786ec4873c3d73d4c7d4

2024-09-23 00:17 UTC, ByunDohwi commented on src/main/resources/application.yml
> +    url: jdbc:mysql://localhost:3306/${DB_URL}
4322cd029cefd9c5be5f62ecf0b71f69e1298100

2024-10-14 07:50 UTC, merged